# Generated by Django 4.2.8 on 2023-12-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_languages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Topics',
        ),
        migrations.AlterField(
            model_name='languages',
            name='language',
            field=models.CharField(max_length=20),
        ),
    ]
