# Generated by Django 4.2.8 on 2023-12-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_rename_languages_language_rename_topics_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
