# Generated by Django 4.2.9 on 2024-01-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
